version: '2.0'
services:

    test_docker:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: test_docker
        ports:
            - "190:80"
        networks:
            test_network:
                aliases:
                    - test_docker
        volumes:
            - .:/var/www

    redis_box:
        image: redis:latest
        container_name: redis_box
        expose:
            - "6379"
        networks:
            - test_network

networks:
    test_network:
        external:
            name: test_network
