parameters:
    #parameter_name: value

services:
    app_bundle.controller.default:
        class: AppBundle\Controller\DefaultController
        arguments: [ '@templating', '@http_client', '%kernel.project_dir%' ]

    dittto.request_logger.alias:
        alias: 'dittto.request_logger.passthrough'

    dittto.request_logger.monolog_channel:
        alias: 'monolog.logger.external_request'

    http_client:
        class: GuzzleHttp\Client
        arguments:
            - handler: '@http_client.handlerstack'
              connect_timeout: 5
              timeout: 5

    http_client.handlerstack:
        class: GuzzleHttp\HandlerStack
        factory: [ GuzzleHttp\HandlerStack, 'create' ]
        calls:
            - [ 'push', [ '@dittto.cached_request.middleware.request' ] ]

    dittto.cached_request.middleware.request:
        class: Closure
        factory: [ '@dittto.cached_request.middleware', 'onRequest' ]
        arguments: [ '@logged_cache_adapter', '@dittto.cached_request.generator.sha1_uri', 5 ]

    redis_cache:
        class: Predis\Client
        arguments:
          - scheme: 'tcp'
            host:   'redis_box'
            port:   6379

    cache_adapter:
        class: Symfony\Component\Cache\Simple\RedisCache
        arguments: [ '@redis_cache' ]

    logged_cache_adapter:
        class: Dittto\CachedRequestBundle\Logger\LoggedCacheDecorator
        arguments: [ '@cache_adapter' ]
        calls:
            - [ 'setLogger', [ '@monolog.logger.external_request' ] ]